raise NotImplementedError
EMAIL_HOST_USER = XXX
EMAIL_HOST_PASSWORD = XXX
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = XXX
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = XXX
SOCIAL_AUTH_FACEBOOK_KEY = XXX
SOCIAL_AUTH_FACEBOOK_SECRET = XXX
SOCIAL_AUTH_TWITTER_KEY = XXX
SOCIAL_AUTH_TWITTER_SECRET = XXX
